apiVersion: v1
kind: Pod
metadata:
        name: pod2
        labels:
                type: frontend
spec:
        containers:
                - name: firstcontainer
                  image: coolgourav147/nginx-custom
