apiVersion: apps/v1
kind: Deployment
metadata:
  name: deplo
  labels:
    type: app
spec:
  replicas: 4
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: deploypod
      labels:
        type: app
    spec:
      containers:
        - name: first deploy
          image: coolgourav147/nginx-custom
