apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: firstrs
        labels:
                first: hello
spec:
        replicas: 4
        selector:
                matchLabels:
                        type: frontend
        template:
                metadata:
                        name: firstpod
                        labels:
                                type: frontend
                spec:
                        containers:
                                - name: fistcontainer
                                  image: coolgourav147/nginx-custom
