apiVersion: v1
kind: Pod
metadata:
        name: firstpod
        labels:
                servicelabel: legend
                type: app
spec:
        containers:
                - name: first
                  image: centos/httpd
