apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: firstrs
        labels:
                first: hello
spec:
        replicas: 4
        selector:
                matchExpressions:
                        - key: type
                          operator: In
                          values:
                                  - app1
                                  - app2
                        - key: end
                          operator: NotIn
                          values:
                                  - backend
        template:
                metadata:
                        name: firstpod
                        labels:
                                type: app
                spec:
                        containers:
                                - name: fistcontainer
                                  image: coolgourav147/nginx-custom
