apiVersion: v1
kind: Pod
metadata:
        name: nginxcontainers
        labels:
                env: prod
                type: app
spec:
        containers:
                - name: nginx1
                  image: coolgourav147/nginx-custom:v2
                  args: ["sleep", "3600"]
                - name: nginx2
                  image: nginx
